import { Inter } from "next/font/google";
import Script from "next/script";
  import './globals.css';
  import './landingPage/Components/Featured.css';
  import './Shop/CSS/normalize.css';
  import './Shop/CSS/icomoon.css';
  import './Shop/CSS/vendor.css';
  import './Shop/CSS/globals.css';
  import './Shop/CSS/searchPopup.css';
  import './Shop/CSS/styleBootstrap.css';
  import './Shop/CSS/header.css';
  import './landingPage/Components/BillBoard.css';
  import './landingPage/Components/casualCollection.css';
  import './landingPage/Components/FlashSales.css';
  import './landingPage/Components/sectionBanner.css';
  import "./aboutus/components/AboutPage/BannerSection2.css";
  import './Shop/CSS/styleMain.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "StudentStack Exchange",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Script src="/js/jquery-1.11.0.min.js" />
        <Script src="/js/plugins.js" />
        <Script src="/js/script.js" />
        </body>
    </html>
  );
}
