import { Inter } from "next/font/google";
import './globals.css';
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "StudentStash Exchange",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://kit.fontawesome.com/267526bcf7.js" crossorigin="anonymous"></Script>
      </head>
      <body className={inter.className}>{children}
      </body>
    </html>
  );
}
